# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 23716e17226d984bd980e1d98c9210e1c1a30f41a62b26a50240609e62e9e99e20008bf1a69261c6d4c312028da8c38a776006d0edb528359f3859226d9d397f

test:
  secret_key_base: 0f568bef937508827bbf3bd722ced6e9bb242a5e5e109b771756a0428a1123574fae40cba7b0df6d52c2780dd77adc02359ee83d4d86ee4d1db83da92513cae0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
